services:
  match-api:
    image: ghcr.io/funnypocketbook/overwatch-stats-collector:main
    ports:
      - "8000:8000"
    environment:
      SECRET: counterwatchisactuallyreallycool
    volumes:
      - "/opt/overwatch-stats-collector/match_data:/app/match_data"
